name: passbot 
version: git 
summary: Go based random password generator- experimental. # 79 char long summary
description: |
    Go based random password generator- experimental.
grade: stable
confinement: strict

apps:
  passbot:
    command: $SNAP/bin/passbot.sh

parts: 
  passbot:
    plugin: dump
    source: .
    
  apps:
    plugin: go    
    go-importpath: github.com/kz6fittycent/go-password-generator
    after: [go]
        




