name: passbot # check to see if it's available
version: '1.0.4+git' # check versioning
summary: Go based random password generator- experimental. # 79 char long summary
description: |
    Go based random password generator- experimental.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs

apps:
  passbot:
    command: go-password-generator
    #environment: 
      #LC_ALL: C.UTF-8
    plugs:
      - home
parts: 
  my-part:
    source: .
    plugin: go
    go-importpath: github.com/kz6fittycent/go-password-generator
    after: [go]
  # need nounlist and adjectivelist to end up IN the snap. Credit to DiddleDan for this one.   
    override-build: |
      snapcraftctl build
      install -T nounlist $SNAPCRAFT_PART_INSTALL/nounlist
      install -T adjective list $SNAPCRAFT_PART_INSTALL/adjectivelist
  
