name: passbot # check to see if it's available
version: '1.0.19+git' # check versioning
summary: Go based random password generator- experimental. # 79 char long summary
description: |
    Go based random password generator- experimental.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs

parts: 
  my-part:
    source: .
    plugin: go
    go-importpath: github.com/kz6fittycent/go-password-generator
    after: [go]
    
    prepare: |
      chmod +x passbot.sh
      
     
apps:
  passbot:
    command: passbot
    plugs:
      - home
